### ISSUE TITLE
表名和字段可以默认成达梦默认的大写吗

### ISSUE THREAD

**Issue by stormlei** [godoes/gorm-dameng#12]

**Comment by iTanken** [comment]
不可以。
- 在**大小写敏感**的达梦数据库实例上，GORM 的 `TableName` 方法返回的表名和 `gorm:"column:column_name"` 标签的列名必需和数据库中的大小写一致。
- 在**大小写不敏感**的达梦数据库实例上，表名和列名可以不用区分大小写，不管大写还是小写都可以查到同一个表或字段。
