### ISSUE TITLE
为什么一定要主键冲突了才算 ON CONFLICT 呢？唯一键索引不算呢？

### ISSUE THREAD

**Issue by yiippee** [godoes/gorm-dameng#15]
Create 的时候为什么一定要主键冲突了才算 ON CONFLICT 呢？唯一键索引不算呢？源码如下：
```
		if hasConflict {
			if len(db.Statement.Schema.PrimaryFields) > 0 {
				columnsMap := map[string]bool{}
				for _, column := range values.Columns {
					columnsMap[column.Name] = true
				}

                                // 为什么一定要主键冲突了才算 ON CONFLICT 呢？唯一键索引不算呢？
				for _, field := range db.Statement.Schema.PrimaryFields {
					if _, ok := columnsMap[field.DBName]; !ok {
						hasConflict = false
					}
				}
			} else {
				hasConflict = false
			}
		}
```

**Comment by iTanken** [comment]
个人理解，`hasConflict` 就是为了判断是否有主键冲突，而只有在主键冲突时才可以调用 `MergeCreate` 根据主键更新数据。而唯一索引冲突就是普通的数据冲突，不应该在驱动层面自动更新非主键冲突的数据，需要调用方自行处理。

> 更多达梦官方驱动相关问题建议前往 [达梦技术社区](https://eco.dameng.com/community/question/) 进行提问。

**Comment by yiippee** [comment]
> 个人理解，`hasConflict` 就是为了判断是否有主键冲突，而只有在主键冲突时才可以调用 `MergeCreate` 根据主键更新数据。而唯一索引冲突就是普通的数据冲突，不应该在驱动层面自动更新非主键冲突的数据，需要调用方自行处理。
> 
> > 更多达梦官方驱动相关问题建议前往 [达梦技术社区](https://eco.dameng.com/community/question/) 进行提问。

mysql 的驱动就支持啊

**Comment by iTanken** [comment]
> mysql 的驱动就支持啊

[sqlserver](https://github.com/go-gorm/sqlserver/blob/master/create.go#L29) 也不支持，可能达梦官方 GORM 驱动是参考的 SQL Server 的 GORM 驱动吧，具体为什么不支持麻烦去 [达梦技术社区](https://eco.dameng.com/community/question/) 进行提问。
