### ISSUE TITLE
更新达梦官方驱动版本 go-20240918

### ISSUE THREAD

**Issue by iTanken** [godoes/gorm-dameng#18]
## Describe the feature 功能描述

⬆️ 更新达梦官方驱动版本 go-20240918

## Motivation 动机

[达梦 Go 驱动源码](https://eco.dameng.com/download/)

- 针对版本 DM8
- 2024/09/18 更新

## Related Issues 相关问题

- [go-20240918.zip](https://download.dameng.com/eco/adapter/resource/go/go-20240918.zip)

**Comment by HubQin** [comment]
请问这个驱动更新后，达梦数据库服务端需要更新吗？ 我们目前服务端使用的版本是：--03134284172-20240527-229704-20093 Pack5
