### ISSUE TITLE
达梦数据库部署为两地三中心方式，该怎么链接？

### ISSUE THREAD

**Issue by KevinLiangX** [godoes/gorm-dameng#4]
你好，很感谢您封装了官方的驱动，现在有个问题， 如果达梦数据库部署的方式 两地三中心的模式， 像java就可以实现  jdbc:dm://ss?yyy=(damengbc1.xian.cloud.crb:5288,damengbc2.xian.cloud.crb:5288,damengbc1.shanghai.cloud.crb:5288,damengbc2.shanghai.cloud.crb:5288,damengbc1.xinjiang.cloud.crb:5288)&login_mode=(1)&logLevel=error
这种咱们是否支持配置？ 还是说这种负载均衡和故障转移，得自己在对接的时候实现？驱动层不知道有没有什么方式？

**Comment by iTanken** [comment]
[官方原生 Go 驱动是支持的](https://eco.dameng.com/document/dm/zh-cn/pm/go-rogramming-guide.html#11.3%20%E8%BF%9E%E6%8E%A5%E4%B8%B2%E5%B1%9E%E6%80%A7%E8%AF%B4%E6%98%8E)：

```url
dm://user:password@GroupName?GroupName=(host1:port1,host2:port2,…)[&propName1=propValue1]…
```

按照官方的规则拼接好 **`dsn`** 后将其传递给 `dameng.Open()` 函数即可：

```go
db, err := gorm.Open(dameng.Open(dsn), &gorm.Config{})
```

或者自己创建 `Dialector`：

```go
dialector := &dameng.Dialector{
    Config: &dameng.Config{
        DSN: dsn,

	VarcharSizeIsCharLength: false,
    }
}
db, err := gorm.Open(dialector, &gorm.Config{})
```

**Comment by KevinLiangX** [comment]
多谢多谢，我后面试试这种方式， 
还有一个问题想资源一下， 就是 DM的写的是域名，但是再初始化的时候，解析的是localhost:端口

import (
	"github.com/godoes/gorm-dameng"
	"gorm.io/gorm"
)

func InitDM(ds string) (*gorm.DB, error) {
	//options := map[string]string{
	//	"schema": "SYSDBA",
	//}
	//dsn := dameng.BuildUrl("SYSDBA", "SYSDBA001", "10.64.7.178", 30236, options)
	db, err := gorm.Open(dameng.Open(ds), &gorm.Config{})

	if err != nil {
		return nil, err
	}
	return db, nil
}
尝试打印了一下ds 确实是这个，dm://SYSDBA:SYSDBA001@10.64.17.63.nip.io:32418?schema=SYSDBA  但是再 初始化表的时候 就报错了
[error] failed to initialize database, got error Error 6001: 网络通信异常	dial address: localhost:32418
stack info:
   1).  github.com/godoes/gorm-dameng/dm8.dm_build_431
    	/home/opsinsight-20240312/vendor/github.com/godoes/gorm-dameng/dm8/a.go:63
   2).  github.com/godoes/gorm-dameng/dm8.dm_build_426
    	/home/opsinsight-20240312/vendor/github.com/godoes/gorm-dameng/dm8/a.go:41
   3).  github.com/godoes/gorm-dameng/dm8.(*DmConnector).connectSingle
    	/home/opsinsight-20240312/vendor/github.com/godoes/gorm-dameng/dm8/n.go:833
   4).  github.com/godoes/gorm-dameng/dm8.(*ep).connect
    	/home/opsinsight-20240312/vendor/github.com/godoes/gorm-dameng/dm8/x.go:160
   5).  github.com/godoes/gorm-dameng/dm8.(*epGroup).traverseServerList
    	/home/opsinsight-20240312/vendor/github.com/godoes/gorm-dameng/dm8/y.go:105
   6).  github.com/godoes/gorm-dameng/dm8.(*epGroup).connect
    	/home/opsinsight-20240312/vendor/github.com/godoes/gorm-dameng/dm8/y.go:64
   7).  github.com/godoes/gorm-dameng/dm8.(*DmConnector).connect
    	/home/opsinsight-20240312/vendor/github.com/godoes/gorm-dameng/dm8/n.go:811
   8).  github.com/godoes/gorm-dameng/dm8.(*filterChain).DmConnectorConnect
    	/home/opsinsight-20240312/vendor/github.com/godoes/gorm-dameng/dm8/zd.go:59
   9).  github.com/godoes/gorm-dameng/dm8.(*reconnectFilter).DmConnectorConnect
    	/home/opsinsight-20240312/vendor/github.com/godoes/gorm-dameng/dm8/zf.go:161
   10).  github.com/godoes/gorm-dameng/dm8.(*filterChain).DmConnectorConnect
    	/home/opsinsight-20240312/vendor/github.com/godoes/gorm-dameng/dm8/zd.go:56
   11).  github.com/godoes/gorm-dameng/dm8.(*DmConnector).Connect
    	/home/opsinsight-20240312/vendor/github.com/godoes/gorm-dameng/dm8/n.go:800
   12).  database/sql.(*DB).conn
    	/usr/local/go/src/database/sql/sql.go:1387
   13).  database/sql.(*DB).PingContext.func1
    	/usr/local/go/src/database/sql/sql.go:850
   14).  database/sql.(*DB).retry
    	/usr/local/go/src/database/sql/sql.go:1538
   15).  database/sql.(*DB).PingContext
    	/usr/local/go/src/database/sql/sql.go:849
   16).  database/sql.(*DB).Ping
    	/usr/local/go/src/database/sql/sql.go:867
   17).  gorm.io/gorm.Open
    	/home/opsinsight-20240312/vendor/gorm.io/gorm/gorm.go:206
   18).  kubegien.org/kg-ops-insight/pkg/db/connection.InitDM
    	/home/opsinsight-20240312/pkg/db/connection/dm.go:13
   19).  kubegien.org/kg-ops-insight/pkg/db.InitDataBaseConnection
    	/home/opsinsight-20240312/pkg/db/database.go:28
   20).  kubegien.org/kg-ops-insight/pkg/db.DatabaseMigration
    	/home/opsinsight-20240312/pkg/db/database.go:55
   21).  kubegien.org/kg-ops-insight/cmd/apiserver/app.RunDbMigration
    	/home/opsinsight-20240312/cmd/apiserver/app/server.go:114
   22).  kubegien.org/kg-ops-insight/cmd/apiserver/app.NewAPIServerCommand.func4
    	/home/opsinsight-20240312/cmd/apiserver/app/server.go:90
   23).  github.com/spf13/cobra.(*Command).execute
    	/home/opsinsight-20240312/vendor/github.com/spf13/cobra/command.go:987
   24).  github.com/spf13/cobra.(*Command).ExecuteC
    	/home/opsinsight-20240312/vendor/github.com/spf13/cobra/command.go:1115
   25).  github.com/spf13/cobra.(*Command).Execute
    	/home/opsinsight-20240312/vendor/github.com/spf13/cobra/command.go:1039
   26).  main.main
    	/home/opsinsight-20240312/cmd/apiserver/apiserver.go:29
   27).  runtime.main
    	/usr/local/go/src/runtime/proc.go:250
   28).  runtime.goexit
    	/usr/local/go/src/runtime/asm_amd64.s:1598
    	
    	不知道该怎么排查了。 这块该怎么排查一下， 我在主机上直接go  run代码 就会报这个错， nslookup是可以解析出来
 [root@k8s-94 ~]# nslookup 10.64.17.63.nip.io
Server:		114.114.114.114
Address:	114.114.114.114#53

Non-authoritative answer:
Name:	10.64.17.63.nip.io
Address: 10.64.17.63

**Comment by iTanken** [comment]
这是应该是本地网络环境问题，我这边没办法看。

**Comment by KevinLiangX** [comment]
回复一下， 达梦go 的 driver不支持 域名，填写域名的话 会更改为localhost, 需要使用 servicename 充当域名当时进行访问。

**Comment by iTanken** [comment]
> 回复一下， 达梦go 的 driver不支持 域名，填写域名的话 会更改为localhost, 需要使用 servicename 充当域名当时进行访问。

感谢反馈。看来是 `n.go` 文件中 `mergeConfigs` 方法的问题（特性 😂）：

https://github.com/godoes/gorm-dameng/blob/d608fc0ec30720da150040327691644ba79bf03f/dm8/n.go#L749-L754

**Comment by iTanken** [comment]
提交 697dab3 已更新 **`20240326`** 版本的 DM 官方驱动：

> 支持在连接串上直接配置动态服务名，使用示例：
> dm://user:password@GroupName?GroupName=(host1:port1,host2:port2,...)
>
> [CHANGELOG.md](https://github.com/godoes/gorm-dameng/blob/main/dm8/CHANGELOG.md)

已发布于 [`v0.0.13`](https://github.com/godoes/gorm-dameng/releases/tag/v0.0.13)：

```shell
go get github.com/godoes/gorm-dameng@v0.0.13
```
