### ISSUE TITLE
sql 为什么不会自动去掉 `` 和 ""

### ISSUE THREAD

**Issue by jaronnie** [godoes/gorm-dameng#8]
## Environment 环境
<img width="1357" alt="image" src="https://github.com/godoes/gorm-dameng/assets/77253497/210bcd11-03a4-46a5-bb9a-03159facc45c">

- [**`oracle database`**](https://endoflife.date/oracle-database) veresion: `XXx`
- [**`gorm-oracle`**](https://github.com/godoes/gorm-oracle/tags) version：`vX.X.X`
- [`go-gorm`](https://github.com/go-gorm/gorm/tags) version：`vX.X.X`
- [`go`](https://github.com/golang/go/tags) version：`goX.X.X`
- `os`: `XXX`
- `arch`: `XXX`

## Your Question 你的问题

如何去掉 sql 中的 `` 和 "", 不然 sql 不合法

```go
func NewGormConn(c config.Config) (*gorm.DB, error) {
	switch c.DataBaseType {
	case "mysql":
		return mysql.Connect(c.Mysql)
	case "dm":
		options := map[string]string{
			"schema":         "SYSDBA",
			"compatibleMode": "Mysql",
		}
		dsn := dameng.BuildUrl(c.Dm.Username, c.Dm.Password, c.Dm.Path, c.Dm.Port, options)
		return gorm.Open(dameng.Open(dsn), &gorm.Config{})
	}
	return nil, fmt.Errorf("unsupported database type: %s", c.DataBaseType)
}

func (m *defaultTSystemDictKeyModel) FindOneByCategoryCode(ctx context.Context, categoryCode string) (*TSystemDictKey, error) {
	var resp TSystemDictKey
	err := m.conn.WithContext(ctx).Model(&TSystemDictKey{}).Where("`category_code` = ?", categoryCode).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
```

**Comment by yiippee** [comment]
双引号(` `)和反引号(" ")都是各自驱动的 quote 语义，mysql 使用反引号，dm使用双引号，算是一种不同数据库的规定，dm是区分大小写的如果没有quote，dm默认是大写，但mysql可以不写。
