### ISSUE TITLE
第一次 Auto migrate 成功，第二次就失败了

### ISSUE THREAD

**Issue by jaronnie** [godoes/gorm-dameng#9]
## Environment 环境

- [**`oracle database`**](https://endoflife.date/oracle-database) veresion: `XXx`
- [**`gorm-oracle`**](https://github.com/godoes/gorm-oracle/tags) version：`vX.X.X`
- [`go-gorm`](https://github.com/go-gorm/gorm/tags) version：`vX.X.X`
- [`go`](https://github.com/golang/go/tags) version：`goX.X.X`
- `os`: `XXX`
- `arch`: `XXX`

## Code 示例代码

```go
func Migrate(db *gorm.DB) error {
	return db.AutoMigrate(&system_dict_key.TSystemDictKey{},
		&system_dict_value.TSystemDictValue{})
}

```

```go

```

**Comment by iTanken** [comment]
你好，我这里在本地和 GitHub Actions 上进行测试都没有报错呢，请问你是报的什么错呢？

- 测试代码：https://github.com/godoes/gorm-dameng/commit/e65e6155c7ca38bef683cd9c11b45503a193af1e
- 测试详情：https://github.com/godoes/gorm-dameng/actions/runs/9393712218/job/25870198380#step:9:13

**Comment by jaronnie** [comment]
好像是因为我的 tablename 带了 `` 导致，没事我这边的 tablename 搞的有问题
